import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import './Legal.css';
import logo from '../../assets/LightReadLogo.svg';

const TermsOfService = () => {
  const navigate = useNavigate();

  return (
    <div className="legal-page">
      <div className="legal-header">
        <img src={logo} alt="LightRead logo" onClick={() => navigate('/')} />
      </div>
      <div className="legal-container">
        <h1>Terms of Service</h1>
        <p className="last-updated">Last Updated: {new Date().toLocaleDateString()}</p>

        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>By accessing and using LightRead's services, including our Chrome extension and website, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.</p>
        </section>

        <section>
          <h2>2. Service Description</h2>
          <p>LightRead provides an AI-powered text summarization service through a Chrome extension. The service processes user-selected text to generate concise summaries using third-party AI APIs.</p>
        </section>

        <section>
          <h2>3. User Responsibilities</h2>
          <p>As a user of LightRead, you agree to:</p>
          <ul>
            <li>Provide accurate and complete information when creating an account</li>
            <li>Maintain the security of your account credentials</li>
            <li>Use the service in compliance with all applicable laws and regulations</li>
            <li>Not attempt to circumvent any limitations or security measures</li>
          </ul>
        </section>

        <section>
          <h2>4. Data Processing and Security</h2>
          <p>By using LightRead, you acknowledge and agree that:</p>
          <ul>
            <li>Text submitted for summarization is processed through public AI APIs</li>
            <li>You should not submit sensitive, confidential, or private information for summarization</li>
            <li>We are not responsible for the security of data processed through third-party AI services</li>
            <li>Original text is only temporarily stored during processing and is deleted when the summary popup is closed</li>
          </ul>
        </section>

        <section>
          <h2>5. AI-Generated Content Disclaimer</h2>
          <p>Users acknowledge that:</p>
          <ul>
            <li>Summaries are generated by AI and may not be 100% accurate</li>
            <li>LightRead is not responsible for any misrepresentation or inaccuracies in AI-generated summaries</li>
            <li>Generated summaries should be verified against the original content</li>
            <li>The service should not be used for critical decision-making without human verification</li>
          </ul>
        </section>

        <section>
          <h2>6. Service Limitations</h2>
          <p>LightRead reserves the right to:</p>
          <ul>
            <li>Impose usage limits based on user subscription tier</li>
            <li>Modify or discontinue any feature of the service</li>
            <li>Update these terms of service with reasonable notice</li>
            <li>Terminate accounts that violate these terms</li>
          </ul>
        </section>

        <section>
          <h2>7. Intellectual Property</h2>
          <p>Users retain ownership of their original content. However, by using our service, you grant LightRead the necessary rights to process your content for summarization purposes. The LightRead extension, website, and brand assets remain the exclusive property of LightRead.</p>
          <p>LightRead's source code is open source and available for review on GitHub. While the code is publicly accessible, it remains subject to the license terms specified in our repository. The open-source nature of our code reflects our commitment to transparency and community collaboration.</p>
        </section>

        <section>
          <h2>8. Limitation of Liability</h2>
          <p>LightRead provides the service "as is" and makes no warranties, express or implied. We are not liable for:</p>
          <ul>
            <li>Accuracy of AI-generated summaries</li>
            <li>Data processed through third-party AI services</li>
            <li>Any direct, indirect, or consequential damages</li>
            <li>Service interruptions or technical issues</li>
          </ul>
        </section>

        <section>
          <h2>9. Changes to Terms</h2>
          <p>We may update these terms from time to time. Continued use of LightRead after such changes constitutes acceptance of the new terms. Users will be notified of significant changes.</p>
        </section>

        <section>
          <h2>10. Contact Us</h2>
          <p>If you have any questions about these Terms of Service, please contact us at support@lightread.app</p>
        </section>

        <div className="legal-footer">
          <Link to="/privacy">View Privacy Policy</Link>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService; 