import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import './Legal.css';
import logo from '../../assets/LightReadLogo.svg';

const TermsOfService = () => {
  const navigate = useNavigate();

  return (
    <div className="legal-page">
      <div className="legal-header">
        <img src={logo} alt="LightRead logo" onClick={() => navigate('/')} />
      </div>
      <div className="legal-container">
        <h1>Terms of Service</h1>
        <p className="last-updated">Last Updated: {new Date().toLocaleDateString()}</p>

        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>By accessing and using LightRead's services, including our Chrome extension and website, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.</p>
        </section>

        <section>
          <h2>2. Service Description</h2>
          <p>LightRead provides an AI-powered text summarization service through a Chrome extension. The service processes user-selected text to generate concise summaries using third-party AI APIs.</p>
        </section>

        <section>
          <h2>3. User Responsibilities</h2>
          <p>As a user of LightRead, you agree to:</p>
          <ul>
            <li>Provide accurate and complete information when creating an account</li>
            <li>Maintain the security of your account credentials</li>
            <li>Use the service in compliance with all applicable laws and regulations</li>
            <li>Not attempt to circumvent any limitations or security measures</li>
          </ul>
        </section>

        <section>
          <h2>4. Data Processing and Security</h2>
          <p>By using LightRead, you acknowledge and agree that:</p>
          <ul>
            <li>Text submitted for summarization is processed through public AI APIs</li>
            <li>You should not submit sensitive, confidential, or private information for summarization</li>
            <li>We are not responsible for the security of data processed through third-party AI services</li>
            <li>Original text is only temporarily stored during processing and is deleted when the summary popup is closed</li>
          </ul>
        </section>

        <section>
          <h2>5. AI-Generated Content Disclaimer</h2>
          <p>Users acknowledge that:</p>
          <ul>
            <li>Summaries are generated by AI and may not be 100% accurate</li>
            <li>LightRead is not responsible for any misrepresentation or inaccuracies in AI-generated summaries</li>
            <li>Generated summaries should be verified against the original content</li>
            <li>The service should not be used for critical decision-making without human verification</li>
          </ul>
        </section>

        <section>
          <h2>6. Subscription and Billing</h2>
          <p>LightRead offers both Free and Pro subscription tiers:</p>
          <ul>
            <li>Pro subscriptions are billed monthly at $5.00 per month</li>
            <li>Subscriptions automatically renew each billing period unless cancelled</li>
            <li>Payment is processed securely through Stripe</li>
            <li>You may cancel your subscription at any time through your account dashboard</li>
          </ul>
          <p><strong>Cancellation Policy:</strong> When you cancel your Pro subscription, you will retain access to Pro features until the end of your current billing period. You will not be charged again, and your account will automatically downgrade to the Free plan. For full details about cancellation, billing periods, refunds, and resubscribing, please see our <Link to="/cancellation-policy">Cancellation Policy</Link>.</p>
        </section>

        <section>
          <h2>7. Service Limitations and Availability</h2>
          <p>LightRead reserves the right to:</p>
          <ul>
            <li>Impose usage limits based on user subscription tier</li>
            <li>Modify or discontinue any feature of the service</li>
            <li>Update these terms of service with reasonable notice</li>
            <li>Terminate accounts that violate these terms</li>
          </ul>
          <p><strong>No Guarantee of Uptime or Availability:</strong> LightRead is provided "as-is" with no guarantee of continuous availability, uptime, or uninterrupted service. The service may experience:</p>
          <ul>
            <li>Temporary or permanent outages</li>
            <li>Technical issues or degraded performance</li>
            <li>Scheduled or unscheduled maintenance</li>
            <li>API integration issues with third-party services</li>
          </ul>
          <p>We are not liable for any service interruptions, and no refunds will be provided for temporary outages or technical issues, except as outlined in our Cancellation Policy.</p>
        </section>

        <section>
          <h2>8. Intellectual Property</h2>
          <p>Users retain ownership of their original content. However, by using our service, you grant LightRead the necessary rights to process your content for summarization purposes. The LightRead extension, website, and brand assets remain the exclusive property of LightRead.</p>
          <p>LightRead's source code is open source and available for review on GitHub. While the code is publicly accessible, it remains subject to the license terms specified in our repository. The open-source nature of our code reflects our commitment to transparency and community collaboration.</p>
        </section>

        <section>
          <h2>9. Limitation of Liability</h2>
          <p>LightRead provides the service "as is" and makes no warranties, express or implied. We are not liable for:</p>
          <ul>
            <li>Accuracy of AI-generated summaries</li>
            <li>Data processed through third-party AI services</li>
            <li>Any direct, indirect, or consequential damages</li>
            <li>Service interruptions or technical issues</li>
          </ul>
        </section>

        <section>
          <h2>10. Service Discontinuation</h2>
          <p>LightRead reserves the right to discontinue or modify the service at any time, with or without notice. In the event of permanent service discontinuation:</p>
          <ul>
            <li>Active Pro subscribers will receive a full refund for any unused portion of their subscription</li>
            <li>Users will be given reasonable notice (at least 30 days when possible) to export their saved data</li>
            <li>All data will be permanently deleted following the discontinuation period</li>
          </ul>
        </section>

        <section>
          <h2>11. Changes to Terms</h2>
          <p>We may update these terms from time to time. Continued use of LightRead after such changes constitutes acceptance of the new terms. Users will be notified of significant changes.</p>
        </section>

        <section>
          <h2>12. Contact Us</h2>
          <p>If you have any questions about these Terms of Service, please contact us at jordan.sinclair@du.edu</p>
        </section>

        <div className="legal-footer">
          <Link to="/privacy">View Privacy Policy</Link>
          {' | '}
          <Link to="/cancellation-policy">View Cancellation Policy</Link>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService; 